"""empty message

Revision ID: 619c7f018407
Revises: 
Create Date: 2018-10-02 18:34:24.970196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619c7f018407'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answerlist', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answerlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anonymous', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
